version: "2"
run:
  modules-download-mode: readonly
  issues-exit-code: 1
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - gochecknoinits
    - noinlineerr
    - wsl
  settings:
    tagalign:
      sort: false
    varnamelen:
      ignore-names:
        - ch
        - id
        - i
      ignore-type-assert-ok: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - funlen
          - lll # Because of the mocked HTTP responses
        path: _test\.go
      - linters:
          - lll # Because of the struct tags
        source: '`.*`'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/weisshorn-cyd/opencti_exporter)
        - blank
        - dot
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
