run:
  modules-download-mode: readonly
  timeout: 2m

output:
  formats:
  - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters-settings:
  nolintlint:
    require-explanation: true
    require-specific: true
  gci:
    skip-generated: true
    sections:
      - standard
      - default
      - prefix(github.com/weisshorn-cyd/opencti_exporter)
      - blank
      - dot
  varnamelen:
    ignore-type-assert-ok: true
    ignore-map-index-ok: true
    ignore-names:
      - ch
      - id
      - i # Iterator
  funlen:
    lines: 99
    statements: 60
    ignore-comments: true
  cyclop:
    max-complexity: 12
    skip-tests: true
  ireturn:
    allow:
      - anon
      - error
      - empty
      - stdlib
      - generic
  tagalign:
    sort: false
  paralleltest:
    ignore-missing: true
  gocognit:
    min-complexity: 50

linters:
  enable-all: true

  disable:
    - depguard
    - exhaustruct
    - exportloopref # Deprecated
    - gochecknoinits

issues:
  exclude-rules:
    - source: "^func Test"
      linters:
        - funlen
    - source: "`.*`"
      linters:
      - lll # Because of the struct tags
  exclude-generated: disable
