name: go
on:
  push:

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Check dependencies are tidy
        uses: katexochen/go-tidy-check@v2

      - name: Install tools
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Install dependencies
        run: |
          go mod download

      - name: Verify dependencies
        run: |
          go mod verify

      - name: Run govulncheck
        run: |
          govulncheck -test ./...

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

      - name: Run tests
        run: |
          go test -failfast -race -coverpkg=./... -covermode=atomic -coverprofile=coverage.txt ./... -timeout 60s

      - name: Build
        run: |
          go build -v -o /dev/null ./...
